## Importing the Library

In [1]:
import numpy as np
import pandas as pd

## Importing the dataset

In [109]:
dataset = pd.read_csv("breast-cancer-wisconsin.data", sep = ',')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [110]:
print(X)
# X.shape

[[5 4 4 ... 3 2 1]
 [3 1 1 ... 3 1 1]
 [6 8 8 ... 3 7 1]
 ...
 [5 10 10 ... 8 10 2]
 [4 8 6 ... 10 6 1]
 [4 8 8 ... 10 4 1]]


In [111]:
print(y)

[2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 4 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 2 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4
 2 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4
 4 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2 4 2 2
 4 2 4 4 2 2 4 2 2 2 4 4 2 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2
 4 4 4 2 4 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4
 4 4 2 4 4 2 4 4 4 2 4 2 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 2 4 2 4 4 4 2 2 2 2
 4 4 4 4 4 2 4 4 4 2 4 2 4 4 2 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 4 2
 2 2 4 4 2 4 2 4 4 2 2 4 2 2 2 4 2 2 2 4 4 2 2 4 2 2 4 2 2 4 2 4 4 4 2 2 4
 4 2 4 2 2 4 4 2 2 2 4 2 2 2 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2 2
 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2
 2 2 2 2 4 2 4 2 4 2 2 2 2 4 2 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 2 2
 2 2 2 2 4 2 2 2 4 2 4 4 4 2 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2
 4 4 2 2 2 4 4 4 2 4 2 4 

In [112]:
X[X == '?'] = np.nan

In [91]:
# X = X.replace(r'^\s*$', np.nan, regex = True)

AttributeError: 'numpy.ndarray' object has no attribute 'replace'

In [113]:
X = X.astype(float)

In [114]:
pd.isna(X).sum()

16

In [104]:
# pd.isnull(X).sum()

16

In [115]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X)
X = imputer.transform(X)

## Preprocessed csv data

In [98]:
dataset1 = pd.read_csv("breast_cancer.csv")
X1 = dataset1.iloc[:, 1:-1].values
y1 = dataset1.iloc[:, -1].values

In [99]:
print(X1)

[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]


In [107]:
X1 = X1.astype(float)

In [68]:
print(y1)

[2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 4 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 2 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4
 2 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4
 4 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2 4 2 2
 4 2 4 4 2 2 4 2 2 2 4 4 2 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2
 4 4 4 2 4 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4
 4 4 2 4 4 2 4 4 4 2 4 2 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 2 4 2 4 4 4 2 2 2 2
 4 4 4 4 4 2 4 4 4 2 4 2 4 4 2 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 4 2
 2 2 4 4 2 4 2 4 4 2 2 4 2 2 2 4 2 2 2 4 4 2 2 4 2 2 4 2 2 4 2 4 4 4 2 2 4
 4 2 4 2 2 4 4 2 2 2 4 2 2 2 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2 2
 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2
 2 2 2 2 4 2 4 2 4 2 2 2 2 4 2 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 2 2
 2 2 2 2 4 2 2 2 4 2 4 4 4 2 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2
 4 4 2 2 2 4 4 4 2 4 2 4 

In [52]:
pd.isna(X1).sum()

0

## Splitting the dataset into training set and test set

In [116]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.75, random_state = 0)

In [117]:
print(X_train)

[[ 4.  3.  3. ...  3.  3.  1.]
 [ 1.  1.  1. ...  2.  1.  1.]
 [10. 10. 10. ...  7. 10.  4.]
 ...
 [ 6.  2.  3. ...  1.  1.  1.]
 [ 5.  1.  1. ...  3.  1.  1.]
 [ 1.  1.  1. ...  1.  1.  1.]]


## Fitting the Logistic Regression model on the training set

In [118]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the test results

In [119]:
y_pred = classifier.predict(X_test)

## Making the confusion Matrix

In [130]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred)*100)

[[324  13]
 [  9 178]]
95.80152671755725


In [128]:
(324+178)/(324+13+9+178)*100

95.80152671755725

## Caculating the Accuracy Score with k-fold cross validation

In [127]:
from sklearn.model_selection import cross_val_score
cvs = cross_val_score(classifier, X_train, y_train, cv = 10) # here cv is number of folds
print("Accuracy: ",cvs.mean()*100,"%")
print("Standard Deviation: ", cvs.std()*100,"%")

Accuracy:  97.12418300653596 %
Standard Deviation:  2.8780442949416996 %
